[package]
name = "has"
description = "A Hack Assembler"
version = "0.1.0"
authors = ["Fred Morcos <fm@fredmorcos.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
env_logger = "0.7"
log = "0.4"
derive_more = "0.99"
derive-new = "0.5"
either = "1.6"
atoi = "0.3"
