[package]
name = "has"
description = "Assembler for the Hack machine"
version = "0.1.0"
authors = ["Fred Morcos <fm@fredmorcos.com>"]
edition = "2018"

[lib]
name = "has"

[[bin]]
name = "has"

[dependencies]
structopt = "0.3"
env_logger = "0.7"
log = "0.4"
atoi = "0.3"
derive_more = "0.99"
either = "1.6"
