max_width = 90
# struct_lit_width = 80
# comment_width = 97
# wrap_comments = true
tab_spaces = 2
edition = "2018"
newline_style = "Unix"
fn_args_layout = "Compressed"
use_field_init_shorthand = true
