name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  lint:
    name: CI on ${{matrix.os}} with the ${{matrix.toolchain}} toolchain
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-18.04
          - ubuntu-16.04
          - windows-latest
          - windows-2019
          - macos-latest
          - macos-10.15
        toolchain: [stable]
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain ${{matrix.toolchain}}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{matrix.toolchain}}
          override: true
          components: rustfmt, clippy
      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features
      - name: Formatting check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check -l
      - name: Documentation build
        uses: actions-rs/cargo@v1
        env:
          RUSTDOCFLAGS: -Dwarnings
        with:
          command: doc
          args: --all-features --no-deps --document-private-items
      - name: Debug check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets --all-features
      - name: Debug build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features
      - name: Tests with debug build
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
      - name: Release check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets --all-features --release
      - name: Release build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features --release
      - name: Tests with release build
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --release
